// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8PDv70pemCCPdmKM6cfs0jmO234Txk8E',
    appId: '1:415975695580:web:87cfde870ac182fdc08019',
    messagingSenderId: '415975695580',
    projectId: 'my-project-album-a6ada',
    authDomain: 'my-project-album-a6ada.firebaseapp.com',
    storageBucket: 'my-project-album-a6ada.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnvo9tegT4Uv4lCc8dJpFpNUzUcRfuNQI',
    appId: '1:415975695580:android:4dead2cc083c7a09c08019',
    messagingSenderId: '415975695580',
    projectId: 'my-project-album-a6ada',
    storageBucket: 'my-project-album-a6ada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClBBsMyearicI0Yx1CDViEAEkzhBkKPvc',
    appId: '1:415975695580:ios:604b53ebbb00521cc08019',
    messagingSenderId: '415975695580',
    projectId: 'my-project-album-a6ada',
    storageBucket: 'my-project-album-a6ada.appspot.com',
    iosClientId: '415975695580-dv1pj3jsdb3evoro8uf3n8ahodrphjlg.apps.googleusercontent.com',
    iosBundleId: 'com.example',
  );
}
